<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 1,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            1 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 2,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            2 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 3,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            3 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Password',
                'edit' => 1,
                'field' => 'password',
                'id' => 4,
                'order' => 7,
                'read' => 0,
                'required' => 1,
                'type' => 'password',
            ),
            4 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Remember Token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 5,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            5 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 6,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            6 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 7,
                'order' => 11,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            7 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 12,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            8 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 13,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            9 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 14,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            10 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 15,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            11 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 16,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            12 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 17,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            13 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 18,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            14 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 19,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            15 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Display Name',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 20,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            16 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 22,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            17 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Role Id',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 23,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'number',
            ),
            18 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 24,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            19 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 25,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            20 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Avatar',
                'edit' => 1,
                'field' => 'avatar',
                'id' => 26,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            21 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Password',
                'edit' => 1,
                'field' => 'password',
                'id' => 27,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'password',
            ),
            22 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Remember Token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 28,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            23 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Settings',
                'edit' => 0,
                'field' => 'settings',
                'id' => 29,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            24 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 30,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            25 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 31,
                'order' => 11,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            26 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Lastname',
                'edit' => 1,
                'field' => 'lastname',
                'id' => 32,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            27 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Image',
                'edit' => 1,
                'field' => 'image',
                'id' => 33,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            28 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'role',
                'id' => 34,
                'order' => 16,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            29 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Phone',
                'edit' => 1,
                'field' => 'phone',
                'id' => 35,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            30 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Fb Id',
                'edit' => 1,
                'field' => 'fb_id',
                'id' => 36,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            31 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Google Id',
                'edit' => 1,
                'field' => 'google_id',
                'id' => 37,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            32 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email Verified At',
                'edit' => 1,
                'field' => 'email_verified_at',
                'id' => 38,
                'order' => 14,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            33 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Restaurant Id',
                'edit' => 1,
                'field' => 'restaurant_id',
                'id' => 39,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            34 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 40,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            35 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 41,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            36 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Address',
                'edit' => 1,
                'field' => 'address',
                'id' => 42,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            37 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Phone',
                'edit' => 1,
                'field' => 'phone',
                'id' => 43,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            38 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Logo',
                'edit' => 1,
                'field' => 'logo',
                'id' => 44,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'image',
            ),
            39 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Slug',
                'edit' => 1,
                'field' => 'slug',
                'id' => 45,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            40 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 46,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            41 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 47,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            42 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 48,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            43 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 49,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            44 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 50,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            45 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Phone',
                'edit' => 1,
                'field' => 'phone',
                'id' => 51,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            46 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Fb Id',
                'edit' => 1,
                'field' => 'fb_id',
                'id' => 52,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            47 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Google Id',
                'edit' => 1,
                'field' => 'google_id',
                'id' => 53,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            48 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Password',
                'edit' => 1,
                'field' => 'password',
                'id' => 54,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'password',
            ),
            49 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Verified At',
                'edit' => 1,
                'field' => 'verified_at',
                'id' => 55,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            50 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Payment Method',
                'edit' => 1,
                'field' => 'payment_method',
                'id' => 56,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            51 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Remember Token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 57,
                'order' => 10,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            52 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 58,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            53 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 59,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            54 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 60,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            55 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Code',
                'edit' => 1,
                'field' => 'code',
                'id' => 61,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            56 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Restaurant Id',
                'edit' => 0,
                'field' => 'restaurant_id',
                'id' => 62,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            57 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Client Id',
                'edit' => 0,
                'field' => 'client_id',
                'id' => 63,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'number',
            ),
            58 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Status',
                'edit' => 1,
                'field' => 'status',
                'id' => 64,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            59 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Payment Status',
                'edit' => 1,
                'field' => 'payment_status',
                'id' => 65,
                'order' => 10,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            60 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Table',
                'edit' => 1,
                'field' => 'table',
                'id' => 66,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            61 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 67,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            62 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Price',
                'edit' => 1,
                'field' => 'price',
                'id' => 68,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            63 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Person Quantity',
                'edit' => 1,
                'field' => 'person_quantity',
                'id' => 69,
                'order' => 13,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            64 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'People For Quantity',
                'edit' => 1,
                'field' => 'people_for_quantity',
                'id' => 70,
                'order' => 14,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            65 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Takeaway',
                'edit' => 1,
                'field' => 'is_takeaway',
                'id' => 71,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            66 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Online Payment',
                'edit' => 1,
                'field' => 'is_online_payment',
                'id' => 72,
                'order' => 8,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            67 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Payment Method',
                'edit' => 1,
                'field' => 'payment_method',
                'id' => 73,
                'order' => 15,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            68 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Payment Id',
                'edit' => 1,
                'field' => 'payment_id',
                'id' => 74,
                'order' => 16,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            69 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Payment Response',
                'edit' => 1,
                'field' => 'payment_response',
                'id' => 75,
                'order' => 17,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            70 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 76,
                'order' => 18,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            71 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 77,
                'order' => 19,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            72 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 78,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            73 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Parent Id',
                'edit' => 0,
                'field' => 'parent_id',
                'id' => 79,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'number',
            ),
            74 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Restaurant Id',
                'edit' => 0,
                'field' => 'restaurant_id',
                'id' => 80,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            75 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 81,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            76 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Image',
                'edit' => 1,
                'field' => 'image',
                'id' => 82,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'image',
            ),
            77 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Active',
                'edit' => 1,
                'field' => 'active',
                'id' => 83,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            78 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 84,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            79 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 85,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            80 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 86,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            81 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 87,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            82 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Description',
                'edit' => 1,
                'field' => 'description',
                'id' => 88,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            83 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Category Id',
                'edit' => 1,
                'field' => 'category_id',
                'id' => 89,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'number',
            ),
            84 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Restaurant Id',
                'edit' => 1,
                'field' => 'restaurant_id',
                'id' => 90,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            85 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Image',
                'edit' => 1,
                'field' => 'image',
                'id' => 91,
                'order' => 8,
                'read' => 1,
                'required' => 1,
                'type' => 'image',
            ),
            86 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Price',
                'edit' => 1,
                'field' => 'price',
                'id' => 92,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            87 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Active',
                'edit' => 1,
                'field' => 'active',
                'id' => 93,
                'order' => 10,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            88 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Quantity',
                'edit' => 1,
                'field' => 'quantity',
                'id' => 94,
                'order' => 11,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            89 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Weight',
                'edit' => 1,
                'field' => 'weight',
                'id' => 95,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            90 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 96,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            91 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 97,
                'order' => 14,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            92 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Restaurant","table":"restaurants","type":"belongsTo","column":"restaurant_id","key":"id","label":"name","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'display_name' => 'Restaurant',
                'edit' => 1,
                'field' => 'user_belongsto_restaurant_relationship',
                'id' => 98,
                'order' => 15,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            93 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Restaurant","table":"restaurants","type":"belongsTo","column":"restaurant_id","key":"id","label":"name","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'display_name' => 'Restaurant',
                'edit' => 1,
                'field' => 'order_belongsto_restaurant_relationship',
                'id' => 99,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            94 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Client","table":"clients","type":"belongsTo","column":"client_id","key":"id","label":"name","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'display_name' => 'Client',
                'edit' => 1,
                'field' => 'order_belongsto_client_relationship',
                'id' => 100,
                'order' => 20,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            95 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Restaurant","table":"restaurants","type":"belongsTo","column":"restaurant_id","key":"id","label":"name","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'display_name' => 'restaurant',
                'edit' => 1,
                'field' => 'category_belongsto_restaurant_relationship',
                'id' => 101,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            96 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Category","table":"categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'display_name' => 'Category',
                'edit' => 1,
                'field' => 'plate_belongsto_category_relationship',
                'id' => 102,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            97 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Restaurant","table":"restaurants","type":"belongsTo","column":"restaurant_id","key":"id","label":"name","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'display_name' => 'Restaurant',
                'edit' => 1,
                'field' => 'plate_belongsto_restaurant_relationship',
                'id' => 103,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            98 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Plate","table":"plates","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"order_plate","pivot":"1","taggable":"0"}',
                'display_name' => 'Plates',
                'edit' => 1,
                'field' => 'order_belongstomany_plate_relationship',
                'id' => 104,
                'order' => 21,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            99 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'admin_belongsto_role_relationship',
                'id' => 105,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
        ));
        
        
    }
}